import type { TimelineEpic } from "@/modules/timeline/types";

export const mockTimelineEpics: TimelineEpic[] = [
  {
    id: "epic-platform-foundation",
    componentName: "Core platform",
    key: "CORE-101",
    summary: "Platform foundation",
    issues: [
      {
        id: "CORE-118",
        key: "CORE-118",
        summary: "Import current Jira state into snapshot tables",
        issueUrl: null,
        componentName: "Core platform",
        epicId: "epic-platform-foundation",
        epicKey: "CORE-101",
        epicSummary: "Platform foundation",
        assigneeName: "Alex Kim",
        assigneeColor: "#83c8ff",
        status: "In Progress",
        isCompleted: false,
        createdAt: "2026-04-05T08:30:00.000Z",
        startAt: "2026-04-07T09:00:00.000Z",
        dueAt: "2026-04-10T12:00:00.000Z",
        resolvedAt: null,
        estimateHours: 12,
        estimateStoryPoints: 5,
        observedPeople: ["Alex Kim", "Nina Sorokina"],
        assigneeHistory: ["Alex Kim"],
        authorName: "Nina Sorokina",
        markerAt: "2026-04-10T12:00:00.000Z",
        markerKind: "DUE",
        pullRequestStatus: "OPEN",
        pullRequestCount: 1,
        commitCount: 3,
        isMissingDueDate: false,
      },
      {
        id: "CORE-121",
        key: "CORE-121",
        summary: "Derive task start date from Jira changelog",
        issueUrl: null,
        componentName: "Core platform",
        epicId: "epic-platform-foundation",
        epicKey: "CORE-101",
        epicSummary: "Platform foundation",
        assigneeName: "Elena Petrova",
        assigneeColor: "#d7f171",
        status: "Done",
        isCompleted: true,
        createdAt: "2026-04-04T10:15:00.000Z",
        startAt: "2026-04-06T09:00:00.000Z",
        dueAt: "2026-04-08T12:00:00.000Z",
        resolvedAt: "2026-04-08T15:00:00.000Z",
        estimateHours: 8,
        estimateStoryPoints: 3,
        observedPeople: ["Elena Petrova", "Nina Sorokina"],
        assigneeHistory: ["Elena Petrova"],
        authorName: "Nina Sorokina",
        markerAt: "2026-04-08T15:00:00.000Z",
        markerKind: "DONE",
        pullRequestStatus: "MERGED",
        pullRequestCount: 1,
        commitCount: 5,
        isMissingDueDate: false,
      },
    ],
  },
  {
    id: "epic-visual-layer",
    componentName: "Timeline UI",
    key: "CORE-130",
    summary: "Timeline visual layer",
    issues: [
      {
        id: "CORE-132",
        key: "CORE-132",
        summary: "Render epic rows with sticky labels",
        issueUrl: null,
        componentName: "Timeline UI",
        epicId: "epic-visual-layer",
        epicKey: "CORE-130",
        epicSummary: "Timeline visual layer",
        assigneeName: "Alex Kim",
        assigneeColor: "#83c8ff",
        status: "In Review",
        isCompleted: false,
        createdAt: "2026-04-06T14:10:00.000Z",
        startAt: "2026-04-08T09:00:00.000Z",
        dueAt: "2026-04-11T12:00:00.000Z",
        resolvedAt: null,
        estimateHours: 10,
        estimateStoryPoints: null,
        observedPeople: ["Alex Kim", "Elena Petrova", "Marta Rossi"],
        assigneeHistory: ["Alex Kim", "Elena Petrova"],
        authorName: "Marta Rossi",
        markerAt: "2026-04-11T12:00:00.000Z",
        markerKind: "DUE",
        pullRequestStatus: "NONE",
        pullRequestCount: 0,
        commitCount: 4,
        isMissingDueDate: false,
      },
      {
        id: "CORE-136",
        key: "CORE-136",
        summary: "Encode assignees with stable palette mapping",
        issueUrl: null,
        componentName: "Timeline UI",
        epicId: "epic-visual-layer",
        epicKey: "CORE-130",
        epicSummary: "Timeline visual layer",
        assigneeName: "Marta Rossi",
        assigneeColor: "#ff9f8c",
        status: "Done",
        isCompleted: true,
        createdAt: "2026-04-05T11:20:00.000Z",
        startAt: "2026-04-07T12:00:00.000Z",
        dueAt: "2026-04-09T12:00:00.000Z",
        resolvedAt: "2026-04-09T15:00:00.000Z",
        estimateHours: 6,
        estimateStoryPoints: 2,
        observedPeople: ["Marta Rossi", "Alex Kim"],
        assigneeHistory: ["Marta Rossi"],
        authorName: "Alex Kim",
        markerAt: "2026-04-09T15:00:00.000Z",
        markerKind: "DONE",
        pullRequestStatus: "MERGED",
        pullRequestCount: 2,
        commitCount: 8,
        isMissingDueDate: false,
      },
      {
        id: "CORE-139",
        key: "CORE-139",
        summary: "Show tooltip with due date, done date, and assignee",
        issueUrl: null,
        componentName: "Timeline UI",
        epicId: "epic-visual-layer",
        epicKey: "CORE-130",
        epicSummary: "Timeline visual layer",
        assigneeName: "Elena Petrova",
        assigneeColor: "#d7f171",
        status: "Selected for Development",
        isCompleted: false,
        createdAt: "2026-04-08T09:45:00.000Z",
        startAt: null,
        dueAt: "2026-04-12T12:00:00.000Z",
        resolvedAt: null,
        estimateHours: null,
        estimateStoryPoints: 3,
        observedPeople: ["Elena Petrova", "Marta Rossi"],
        assigneeHistory: ["Elena Petrova"],
        authorName: "Marta Rossi",
        markerAt: "2026-04-12T12:00:00.000Z",
        markerKind: "DUE",
        pullRequestStatus: "NONE",
        pullRequestCount: 0,
        commitCount: 0,
        isMissingDueDate: false,
      },
    ],
  },
];
